### ISSUE TITLE
Apps fail to print without CREATOR OWNER permissions on printer

### ISSUE THREAD

**Issue by CNWatkins** [zniezelski/Printerceptor#10]
I have a couple of applications that fail to print preview or print when a user is given full access to the printer. After some troubleshooting I found if I add CREATOR OWNER Manage documents permissions to the printer, then the applications work as expected.

I have upgraded to version 4 and tested with the same result.

Is it easy to change the permissions assigned to the printer to include CREATOR OWNER Manage documents?

**Comment by zniezelski** [comment]
CMWatkins,

Thanks for reporting this behavior. You can add "Creator Owner" to the security by changing the lines "$Users = @($user,'system')" to "$Users = @($user,'system','creator owner')". It looks like there are two lines in the script.

This will add "creator owner" with the same security as the other users (Manage printer). Let me know if that helps. If it must be "Manage Documents" let me know and i'll try to figure out the access mask for that permission.

the script is located "C:\program files\printerceptor\printer.ps1". Be sure to edit with administrative privileges with your editor.

Thanks,

Zach

**Comment by CNWatkins** [comment]
My user has finally got around to testing this for me, and reports the problem still exists. So it appears CREATOR OWNER does require "Manage Documents" permission.

**Comment by zniezelski** [comment]
Thanks for the update. Could you tell me which program the user is using that causes this problem?

I found this KB article https://support.microsoft.com/en-us/help/3139649/print-job-fails-if-creator-owner-is-removed-from-windows-server-2012-r2-or-windows-server-2012 it might fix the problem. I'll also work on adding that permissions to the queue.

Zach

**Comment by CNWatkins** [comment]
Thanks for the quick response!

There are two programs, both payroll applications. Ace Payroll (www.acepay.co.nz) and e-PayDay (www.e-payday.com.au).

The server these are installed on is running Windows Server 2008 R2, so that fix doesn't apply unfortunately.

**Comment by zniezelski** [comment]
CMWatkins,

I changed the script to add "creator owner" with "manage documents" permissions to the re-created queues and put it in the new release 4.1. Can you please re-install with the new release and let me know if it works for you or not?

Thanks,

Zach
