### ISSUE TITLE
Windows 7 32-bit (No 32-bit Installer)

### ISSUE THREAD

**Issue by dog66** [zniezelski/Printerceptor#11]
Hi!

I need to try your script on a Windows 7 32-bit PC, but it won't install on 32-bit system. Any solutions for that.

Kind regards, Gregor

**Comment by zniezelski** [comment]
I have never tried it on a 32bit OS or Windows 7. Maybe try unpacking the .exe with winrar and run the install.bat

Zach

**Comment by zniezelski** [comment]
I'm preparing a 32bit windows 7 machine to test on and see what it does.

Zach

**Comment by zniezelski** [comment]
The installer doesn't open because winrar 64bit was used to package it. Once I get my test machine fully patched i'll test further and if everything works i'll make a 32bit installer.

Thanks for reporting this behavior.

Zach

**Comment by zniezelski** [comment]
Gregor,

I created an installer with 32bit version of winrar and tested in Windows 7 32bit with success. Please give it a try and let me know if you need further assistance.

Thanks,

Zach

**Comment by dog66** [comment]
Thanks Zack. I will test it tomorrow and send you feed back.
Thank you for your superfast response.
Kind regards, Gregor
