### ISSUE TITLE
Attmepted to use Printerceptor but seemed to fail - Registry Path Problem Version 4.2 Release

### ISSUE THREAD

**Issue by zerotechz** [zniezelski/Printerceptor#12]
I have been having an issue with trying to keep permissions from resetting everytime a user logs out of remote desktop and back again..When the permissions reset the printer will not print..I installed Printerceptor and watched your youtube video as to how to set up but upon logging back in it didnt work

**Comment by zniezelski** [comment]
What happens? Do  you get an error? 

Is easy print disabled? https://www.youtube.com/watch?v=VinNQ94PdNA

try this if the re-created printer is disappearing https://youtu.be/zUdCcrgMJ9Y

**Comment by zerotechz** [comment]
easy printer isn't configured..I had to create the "Everyone" group on my DYMO Labelwriter printer and give it full permissions just to be able to access the settings and change the ports to make it work...Upon setting the "everyone" permissions I was extremely happy because finally the DYMO worked..Upon signing out then back in I noticed the "everyone" group completely gone and permissions defaulted back thus the printer unusable..I had hope that your script would resolve this issue and save the "Everyone" permissions upon sign in..The only error I see when trying to print from DYMO Labelwriter is it couldnt print but upon resetting the "everyone" permissions and resetting the port and resetting the "share this printer" again it prints very well

**Comment by zniezelski** [comment]
Is the Dymo a redirected printer?

**Comment by zerotechz** [comment]
Yes it is and hooked USB to local workstation...Driver installed to local and driver installed to server..Both drivers match as well and 64 bit..Printerceptor actually sees it..

**Comment by zniezelski** [comment]
Does printerceptor rename the printer? Could you give me a link to the driver? i'll give it a test and see what its doing.

Do you need "everyone" to have permission to the printer or just the logged in user?

What is the operating system.

Thanks,

Zach

**Comment by zerotechz** [comment]
I have to work on their server at night so I'm not at their office
currently. During the day they are in production...When I check under
devices and printers it doesn't seem to have renamed the driver...The
driver I am using is for DYMO Labelwriter 450 turbo..I'm not using the
newest driver but instead running the Windows 8.5 driver.
HTTP://download.dymo.com/dymo/Software/Win/DLS8Setup.8.5.0.exe

**Comment by zerotechz** [comment]
Technically I have 2 of these Dymos I LL have to install..One inside of a
mobile RV so if I can give each user full permissions I'd be happy

**Comment by zniezelski** [comment]
I installed the driver on my test machine and it seemed to work. The printer name should change to *Printername* - *user* by default when the printer is re-created with full access.

is "Dymo labelWriter 450 Turbo" check in the right "Give full access to printer(s)" section?

what port change do you need to be able to make?

Zach

**Comment by zerotechz** [comment]
Dymo is checked on the right side but it isn't renaming to that...Actually
the name isn't changing at all..I chose 2 ports in server can't remember
the ts port actually or the other port until I get in tonight but local
port was a virtual USB001

**Comment by zerotechz** [comment]
Another thing I noticed was after saving the first time with Printerceptor
I went into options after opening again and noticed the paths fields were
blank that led to CSV viewer and exe tool...On main page up in the top I
noticed the top 2 fields were blank as well...

**Comment by zniezelski** [comment]
The "Printer Name Format" and "Regular Expression" fields should not be blank. If they are blank, its sounds like its unable to open the registry keys.

Maybe try running the installer again.

There should be registry keys at HKEY_LOCAL_MACHINE\SOFTWARE\Printerceptor

**Comment by zniezelski** [comment]
Please send me some screen shots of what is doing and show the options you are trying to change. Please upload to dropbox/onedrive or something because the github box sometimes doesn't show pictures.

Thanks,

Zach

**Comment by matt-jacobson** [comment]
I'm trying printinterceptor for the first time and I'm having the same issue with the registry settings not seeming to be created.  I'm on server 2016.  The installer runs as admin, directory and tasks are created, but no registry entries.  On first launch (from the installer) the UI has values in the regex and such, but relaunching it they're empty (as are the options).

**Comment by zerotechz** [comment]
Tonight I LL uninstall everything then reinstall I LL snapshot the process
upload images to cloud and email them to you

**Comment by zniezelski** [comment]
Matt,

Can you go into "options" and click "restore default" and see its able to work after that? I'll test on 2016 and see if I can make the same problem happen.

Thanks!

Zach

**Comment by zerotechz** [comment]
When I first ran the program those fields weren't blank however it also did
not rename printer and of course as said did not fix the issue of saving
permissions upon log out and log back on

**Comment by zniezelski** [comment]
Ok, I figured out whats going on. I used winrar 32bit for the installer to make it work for someone that uses 32bit windows. The 32bit installer is putting the keys into the wow32 folder on 64bit systems which is not good. I just made 32bit and 64 bit installers and put it on the release download section. Please re-install with the appropriate installer.

Thanks for reporting this problem!

Zach

**Comment by zerotechz** [comment]
I have uninstalled the older 32 bit version and installed the 64 bit now.. The good news is that when my user logs on the printer properties are not greyed out and she has privileges to the settings but upon new login it doesnt remember the settings still and defaults back to its original settings ..This makes the DYMO not functional until the settings are changed again such as sharing,ports..It has also renamed the DYMO printer as well but how do I get it to remember the settings so the printer is functional upon a new sign in ?

**Comment by zniezelski** [comment]
Please send me screenshots of the settings you need to change on the queue and retain.

Thanks,

Zach

**Comment by zerotechz** [comment]
First image everytime the user logs back in The "share this printer" box has to be checked again
[https://drive.google.com/file/d/0B8kyJsYz3UazUF9YQzRsTTFaMDA/view?usp=sharing](https://drive.google.com/file/d/0B8kyJsYz3UazUF9YQzRsTTFaMDA/view?usp=sharing)

second pic The user has to recheck the correct ports again -uncheck "bidirectional support" and recheck "enable printer pooling"
[https://drive.google.com/file/d/0B8kyJsYz3UazV0lnQmV0bi1pZHM/view?usp=sharing](https://drive.google.com/file/d/0B8kyJsYz3UazV0lnQmV0bi1pZHM/view?usp=sharing)


This may be my error not Printerceptor but I just opened "Advanced Policies" in printerceptor and noticed under "client Name" field that the name from local station is showing..I apologize in advance but my first time in the cloud servers and wondering if permissions are the issue
[https://drive.google.com/file/d/0B8kyJsYz3UazeHNuX1l3TlQzdEU/view?usp=sharing](https://drive.google.com/file/d/0B8kyJsYz3UazeHNuX1l3TlQzdEU/view?usp=sharing)

**Comment by zerotechz** [comment]
Disregard the images it works !!!! very very well to I might add..Thank you for this script saved my butt..By chance though - I have another DYMO Labelwriter printer that I havent installed yet on another workstation that will be placed in another area and hooked to a different workstation under a different user..Is it possible to run that Labelwriter using this script separately from this Labelwriter now running in office ?

**Comment by zniezelski** [comment]
I'm glad you got it figure out. The other LabelWriter should work the same way, it will re-create the printer and you will need to set the settings like you just did.

Let me know if you need further assistance.

Thanks,

Zach

**Comment by zerotechz** [comment]
Friday night I thought I had this issue resolved..I placed a shortcut to Printerceptor also on the other users PC that also has a DYMO Labelwriter hooked up by usb as well to her PC..These 2 Dymo's share the same Dymo driver but Noticed in the other users settings that it had picked up her port so I clicked save and the Dymo and her other printer worked great...I signed out and back in several times to both PC's friday night and it was successful..Both had retained their settings perfectly.This morning I get a call from their office and they couldnt print from DYMO's.. I remoted into their system and noticed that some settings had changed again - The box that was checked to "share printer" was unchecked, The "bidirectional" box was checked again but needed to be saved as unchecked.Also the setting in printing preferences such as "landscape" instead of "portrait was back to "portrait" and type of label switched back to "address" instead of "badge label". However I noticed in certain software that uses this printer it had retained its settings such as "DYMO labelwriter 450 turbo-Micki"..Also I noticed on the local printer the box to share printer was unchecked as well...Any ideas on why it cant save these settings ?

**Comment by zerotechz** [comment]
Today it seems other printers are now affected as well..Issue with the Canon Printer that was stable before Printerceptor was installed..Call from client today stating they couldnt use the Office Canon printer now..I went there and noticed that the DYMO labelwriter had "dymolabelwriter 450 turbo-Holly" "dymo labelwriter 450 turbo-Micki" and now a new instance of just "Dymo Labelwriter 450 Turbo"...There are only 2 people that work in this office and share the DYMO printer..Each have a physical DYMO attached to their own device and seems to work great after I reset the settings..I can even sign them out and then back on several times the night I fix the issue with no problems - yet it never seems to fail the next day when they come in and log on that neither DYMO works- it has reset itself to default settings for both.....I noticed today that upon clicking the canon printer to print it seems to send it to fax

**Comment by zerotechz** [comment]
I read in another forum where you speak of this :  
           **Seeing Other User's Printers Problem
there is a scheduled task that inserts attributes into the printers that Printerceptor creates that give the locally created printer the same "hiding" as a redirected printer. It does this using the registry and requires the print spooler to restart for the change to apply. This only needs to be set on the queue 1 time and then users do not see it. I don't know of a way to make the change without restarting the spooler. This task happens early in the morning and checks to make sure there are no active connections that will be disrupted. Users will see newly created printers until the task runs once.**
           So far at night I have managed to set their printers up and they run great even if I sign them out and log back in while I am there but when they come in the next day around 9 am the printers seem to reset themselves again and they dont work...Is their something causing this issue through the night ?

**Comment by zniezelski** [comment]
I played around last night and was unable to make the problem happen on my test machine. Can you send me a screenshot of the security tab on the print queue? The problem probably has something to do with the isolation task that runs early in the morning since you see the problem directly the next day. Try going into task scheduler and disable the task "Printerceptor - isolate" and see if the problem stops occurring.

The task makes it so everyone cannot see the re-created printer and then restarts the print spooler.

You might be seeing the problem occur after the print spooler restarts. If that is the case, the problem will probably occur when the server is rebooted.

I'm curious to see the security tab because maybe its missing something and not saving correctly in the spooler settings.

Zach

**Comment by zerotechz** [comment]
I'll be going into their office within the next hour..I def know that whatever it is has to be something simple I overlook because I have had everything up and running..I logged out and back in several times friday night with no issues but next day they were unable to use again..All I know at this point is if I can get this up and done and for your time I've got no issues donating $100 your way once they pay their bill lol

**Comment by zerotechz** [comment]
Just disabled "printerceptor-isolate" tonight to see what that would do after I reset everything and got it back up working...As far as permissions set - I have added the group "Everyone" to everything local and to the DYMO ..My set up with the DYMO is I have installed the driver to the server and have 2 DYMO Labelwriters attached to 2 different workstations local by USB..When I run printerceptor on one local it names the DYMO correctly as "DYMO labelwriter 450 turbo-Holly". I then go to the other PC and run Printerceptor and it defines the other attached DYMO as "DYMO labelwriter 450 turbo-Micki"..This seems correct so I click save ..At that time I can sign out and sign in on either PC and have no issues with any printers but as said after 9 am when they come in it seems the printers are screwed up ? One thing I never thought about was both signed in at the same time and is that possibly the issue ?

**Comment by zniezelski** [comment]
Did after 9 AM happen yet? Does it still not work?

As long as the user is not logging into multiple terminal sessions with the same username, there should be no problem with both users logging in.

I know the "everyone" permissions will be overwritten when the user logs off and back on. If you really need the everyone permissions, replace C:\program files\printerceptor\printer.ps1 with the one in the zip file. I modified the script to add "Everyone" to all re-created queues. 
 
[printer.zip](https://github.com/zniezelski/Printerceptor/files/958169/printer.zip)

**Comment by zniezelski** [comment]
Why is the printer shared on the terminal server? can you tell me about that setup?

Thanks,

Zach

**Comment by zerotechz** [comment]
yes just received a call 30 minutes ago that the DYMO'S arent working again..Basically both printers are DYMO labelwriter 450 turbos so I installed the one driver into the server to be used by both DYMO's..For instance Micki uses a physical DYMO at her workstation and Holly does as well...One of these DYMO's is located inside of a mobile rv unit and the other inside an office...Each user can only log into terminal session one time..If the user logs into another Workstation as their same username it boots them from their other login device...Just remoted in and see Holly's Dymo in the control panel as well as in print server but under a certain software they use the DYMO isnt even an option..Also logging into printerceptor and going to print management I notice print management setting then printer server settings as well...Just terminated my remote session but it seems that the printer management settings on the ports are wrong and the print server settings may have retained ? I might be hallucinating now but do think so..I'm headed there now to fix it again temporarily until tonight once again I guess

**Comment by zerotechz** [comment]
Went in there earlier today and fixed the office DYMO -IT WAS UP AND RUNNING. Will be going back in in about an hour to check things out..I'm going to see if the DYMO is still working in the office now as well..Basically I do see with Printerceptor that now my printer settings are not greyed out and the user has full permissions but I have yet to see Printerceptor work past 9 am..I can get it running very nicely at night on both Dymo's and sign out then back on 9 or 10 times to test the setup and itll work great however it never fails that the next morning it still doesnt work until I go back in at night and do it all over again...But I realize now that it works for me nightly yet I have made no progress for the client..I disabled "Printerceptor-isolate" last night and that made no difference...Running client side printers shared off same driver in server but Printerceptor has renamed the printers to appropriate names so it does name them and it does show it can work - it just cant make it as a stable solution because my client yet has the opportunity to see it work

**Comment by zniezelski** [comment]
are you able to make the problem occur by rebooting the server or restarting the print spooler service?

Zach

**Comment by zniezelski** [comment]
Printerceptor will remove security when the printer is no longer active in the system. It does this so the local printer does not display if the user logs into a computer a different computer that doesn't have the printer.

to see if this part of the script is giving you trouble, logoff the users that have the dymo, login as a user that doesn't have the dymo and wait until the printerceptor task stops running. You can see the tasks state in "options" on the printer UI.

Zach

**Comment by zniezelski** [comment]
Is it possible to give me remote access to the system? I could take a look at it if its possible.

Thanks,

Zach

**Comment by zerotechz** [comment]
I'm running this instance through Amazon AWS...EC2 instance Windows server
2012 ...I'm going to contact them tonight to see if they are rebooting
nightly...I would hope they aren't because I def am not...I LL check the
spool again tonight but have tried that recreation a few times so far and
it wasn't the issue

**Comment by zerotechz** [comment]
I can give you remote access if you like to check it out..There are only 2 licenses under their remote set up but I can give you one of their usernames privately if you like or teamviewer as well

**Comment by zniezelski** [comment]
RDP and Teamviewer Would be good. You can email the info to zniezelski@lvtech.net

Thanks,

Zach

**Comment by zerotechz** [comment]
I'm within 10 minutes of their office...I LL give you an email with
TeamViewer ID NUMBER and passcode

**Comment by zerotechz** [comment]
Just leaving an update after the help you provided me last night that the issue seems to be resolved..I talked with the client a few minutes ago and this morning as well and they report the Dymo Lablewriters have been working all day long with no issues . I'd say that this issue was error on my behalf and not the Printerceptor script but more of the settings I had created..Thank you for your help and for this script because without this script there would have been no way these printers would have functioned the way the client needed them
