### ISSUE TITLE
High Resource Usage on Server2016

### ISSUE THREAD

**Issue by emjayelle** [zniezelski/Printerceptor#13]
Hi Zach,

I've been using your script to persist printer names.  It seems to be working in that most of the printers are renamed correctly.

However, the script seems to put a very large CPU load on the server and most of the time runs at around 20% CPU usage...
I'm running Server 2016.

In your trouble-shooting instructions, you talk about removing "System permissions may resolve the problem" - i'm not sure if I understand this bit correctly?  Do i remove 'System' permissions from all printers?

Should i see the script continuously running?
The server is used by 15 people, who do randomly log on and off during the day, but not with 'high frequency'.

Any other suggestions with regards isolating the performance issue?
As far as I'm aware IPP printing is not installed.

Anything else I need to let you know?
Assistance would be highly appreciated...

Regards
Matt

**Comment by zniezelski** [comment]
The removing system permission is only if you have IPP printers. 

The script loops a bunch of times when a user logs on or connects. 

You can play around for the round passes and wait time under "options". To limit the amount of time it runs. 

Do you have a ton of printers? What are the server specs?

Zach

**Comment by emjayelle** [comment]
Hi,

Didn't expect a reply so quickly - :-)

Its a VM, 12GB RAM, 4 x Xeon CPU @ 2.4GHz.
Yes - there are a ton of printers locally configured on each users local machine...

**Comment by emjayelle** [comment]
What would you recommend for "Amount of Round Passes" and "Additional wait time in seconds between rounds"?

Also - i assume if a printer gets renamed and setup, nothing will delete that printer if its no longer valid?
Assuming this is the case - any recommendations on how to 'scavenge' for 'stale' printers?

Again - thank you for the script and your assistance

**Comment by zniezelski** [comment]
Thanks for reporting this behavior. Try 2 rounds with 5 seconds wait. The script needs to run long enough for the redirected printers to populate. When the script renames a print, it adds more rounds automatically. 

If users report trouble then increase the rounds. I think the most resource intense part of the script is where it gathers all the printers on the system using WMI.

I'll keep this issue open and see what I can do to make it better.

Thanks,

Zach

**Comment by emjayelle** [comment]
Thanks for the feedback.  Have made the changes - will monitor.
Would 'stale' printers on the local machine slow things down?  i.e. if all the unnecessary local printers are removed - will this improve things?

**Comment by emjayelle** [comment]
Another question - what happens if Printerceptor is run under one of the user accounts?  Will this 'complicate' things or possibly setup multiple tasks in the scheduler?  Could this be part of the problem?

**Comment by emjayelle** [comment]
Some feedback;
Disabled Windows Defender and performance also significantly improved.

**Comment by zniezelski** [comment]
emjayelle,

Do you feel the performance of the script is acceptable with windows defender disabled?

Thanks,

Zach
