### ISSUE TITLE
Advanced Policy - Default Printer Action

### ISSUE THREAD

**Issue by zniezelski** [zniezelski/Printerceptor#14]
Doesn't seem to work on a network shared Printer. Need to look into this.

**Comment by ValkNoSodium** [comment]
Hi.

I tried your solution everything worked fine but in a customer's office he has two pc that shares a local printer and when they connect to the rdp session two printers are generated but only one works. Maybe this could be related to this issue?

**Comment by zniezelski** [comment]
It might be a different issue. Is the same RDP user logging in on both hosts?

**Comment by ValkNoSodium** [comment]
No, one log as "CTY1" and the other as "CTY2" and we have the PRINTER-CTY1 and PRINTER-CTY2 but the user that is logged as CTY1 can not print. I tried sharing the PRINTER-CTY2 and worked but when CTY2 logged off and logged in the sharing property was removed.

**Comment by zniezelski** [comment]
You won't be able to share the redirected printer and have the sharing attribute stick. Can you share the printer outside of the terminal server on the other host?

**Comment by ValkNoSodium** [comment]
Yes, the printer is shared on the other host.

**Comment by zniezelski** [comment]
what "Printer Name Format" are you using?

**Comment by ValkNoSodium** [comment]
![printerceptor](https://user-images.githubusercontent.com/7682135/34738418-8984e06c-f53e-11e7-8a3b-1c6601a26e5f.JPG)

**Comment by zniezelski** [comment]
I'll see if I can re-create the issue. Please give me as much information about the setup as possible. If you send me some screenshots, it may be helpful.

Thanks,

Zach
