### ISSUE TITLE
Printers are not being deleted/renamed - PowerShell Execution Policy

### ISSUE THREAD

**Issue by SPLNTZ** [zniezelski/Printerceptor#16]
Hello,

I am working in Windows Server 2008r2 (Updated.)  
I have installed the .net 3.5 in the features. 
I downloaded and installed the powershell version 3.0. 
I disabled easyprint driver in gpedit (user and computer.) 
edit: I also gave the printer manager Everyone Manage server permissions
Added powershell executables to the printerceptor folder in the program files.  
The tasks in task scheduler were created and the program does show all my drivers.  
I am using us language ( \(redirected (\d+)\))  and the test shows my printers with the redirect at the end.

In the options Current State is Ready and when I click Run it does go into running for a second and then goes back to ready.   I did change the users on the tasks while trying to trouble shoot this to administrator of the local machine.  Not sure where to go from here.

What am I doing wrong?

Thanks

SPLNTZ

![image](https://user-images.githubusercontent.com/29932722/27888186-95fe94ac-6199-11e7-87cd-d64e515fdadc.png)

**Comment by zniezelski** [comment]
The task must run under the system account because the owner is system on redirected printer security.

Does task scheduler show an error after it is run?

If it stops real quick when running without error, please try running the script the task runs manually and report output. Sounds like it is stopping unexpectedly.

Thanks,

Zach




Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by SPLNTZ** [comment]
![image](https://user-images.githubusercontent.com/29932722/27924467-3fd12480-6236-11e7-8f45-884429ac8646.png)

I set the task scheduler user to SYSTEM.  It still did not run and gave me a code 0x1

![image](https://user-images.githubusercontent.com/29932722/27924543-8b7b46e0-6236-11e7-8af9-4fc935bb05c9.png)

In the image at the top it says it's the script isn't digitally signed so I'm betting that's where my problem lies.   

Thanks

SPLNTZ

**Comment by zniezelski** [comment]
Splintz,

Your PowerShell is configured to only run digitally signed scripts.

Open powershell and run "set-ExecutionPolicy bypass" Then give it another try.

Zach

**Comment by SPLNTZ** [comment]
You sir are the man!  Many thanks!!!!! You have solved a problem that I have been fighting with for years.  

Thanks

SPLNTZ

**Comment by zniezelski** [comment]
Awesome! I'm glad it worked out for you. Let me know if you need further assistance.

Zach
