### ISSUE TITLE
Support Windows Server 2016

### ISSUE THREAD

**Issue by joaommvsoares** [zniezelski/Printerceptor#17]
Can't put it to work in Windows Server 2016.
Incompatible?

**Comment by zniezelski** [comment]
It works on 2016. What is it doing? Do you have the printer specific drivers installed and easy print disabled?

Thanks,

Zach

**Comment by joaommvsoares** [comment]
Hello,
Thanks for replying!

Yes, I have instaled on WinServer2016 your software and the driver for my
printer and Easy print is disabled.
But still nothing Works




The only thing that was slightly diferent was permissions on printer
management. I was unable to check Special permissions:

I did it in Advanced mode:

On your software:





What's missing? What i'm doing wrong?

Thanks again,
João Miguel Soares

2018-04-26 12:00 GMT+01:00 zniezelski <notifications@github.com>:

**Comment by zniezelski** [comment]
Please tell me which print driver is being used by the printer.

Is the server on a workgroup or domain?

are you looking to re-create the printer with full permission or only rename it?

Thanks,

Zach

**Comment by zniezelski** [comment]
which language is used? If you test the regular expression, does it show printers that are present under the current logged in user?

**Comment by joaommvsoares** [comment]
The driver is the same on the server and on the "client".

The server is in Workgroup (it's only a test for now)

"*are you looking to re-create the printer with full permission or only
rename it?"*
For now, i just want to rename it,,,

Language: Server EN, client PT (portuguese)

Testing the regular expression:

Can you see the images?

Thanks.
João Miguel Soares

2018-04-26 14:54 GMT+01:00 zniezelski <notifications@github.com>:

**Comment by zniezelski** [comment]
I can't see the images

**Comment by joaommvsoares** [comment]
That explains it....

I took some screenshots with the properties that you where asking... then
you asked me again... :)
Is there a mail where I can send you these emails?



2018-04-26 15:25 GMT+01:00 zniezelski <notifications@github.com>:

**Comment by zniezelski** [comment]
please send to zachary.niezelski@gmail.com

Thanks,

Zach
