### ISSUE TITLE
Multi session per user, printer renaming

### ISSUE THREAD

**Issue by yannkraw** [zniezelski/Printerceptor#18]
Hi,
I have an specific issue
I'm on windows 2016 domain with RDS deployement.
I use User RDS licensing with multi session per users.
I use %printername% On %clientname%

When different client use same login printers with same name on clients, the last one called %printername% On %clientname1% On %clientname2%

I think I can change the template or printer names.  But I it's work natively, that was perfect !

**Comment by zniezelski** [comment]
yannkraw,

Thanks for reporting the issue. I don't think I ever tried the script with multi session per user. I'll try re-creating the issue and troubleshooting.

Zach

**Comment by zniezelski** [comment]
Please try making this change to "C:\Program Files\Printerceptor\printer.ps1"
search for "#Identity is static new name used to identify when name scheme changes occur"

and change the line below it to:

"$identity = $CleanName + "-" + $ClientName"

in printerceptor, go to options and make sure the task is ended and the status is "ready" then give it a try.

Thanks,

Zach

**Comment by yannkraw** [comment]
Thanks for the very quick reply Zach,
I test this fix asap.
I send you feedback

**Comment by zniezelski** [comment]
Have you had any success?

Thanks,

Zach

**Comment by zniezelski** [comment]
yannkraw,

were you able to get this working?

Thanks,

Zach
