### ISSUE TITLE
Ability to rename Easy Print printers

### ISSUE THREAD

**Issue by imkryz** [zniezelski/Printerceptor#19]
Hi there!

Thanks a lot for your hard work. This tool looks awesome. I'm new to the whole scripting word and I didn't know that you could have a GUI with your PowerShell scripts. That's pretty cool.

Is there a way to use this tool to rename Easy Print printers? We have a lot of printers and right now they all work perfectly with Win2016 and Easy Print. The problem is that we need to standardize the printer names to something like "%printername% - %username%", but it looks like Easy Print is not supported with this tool.

Have you encountered any issues with this tool and Easy Print printers? Are you planning to add that feature or have you thought about it?

Again, thanks a lot for your hard work. I know programming requires a lot of effort and I really appreciate you sharing this tool.

Thanks!

imkryz

**Comment by zniezelski** [comment]
imkryz,

Thanks for your message. The tool unfortunately will not work with the easy print driver. When it runs with the easy print driver, it doesn't print and gives an error when viewing the printer properties.

There seems to be some kind of mapping that happens between easy print and the TS ports that happens actively with the print spooler and I haven't been able to figure out how to make it work.

Zach

**Comment by imkryz** [comment]
Zach,

Thanks for your response.

I experimented a little bit and even changing the Easy Print printer name with Print Management causes the printer to stop working.

I hope Microsoft fix this in the future.

Thank you!
