### ISSUE TITLE
Regular Expression in 2016 Server Spanish

### ISSUE THREAD

**Issue by ManoloGA** [zniezelski/Printerceptor#20]
Hi, in 2016 Server the regular expression have been changed including an "(s)". I've tried to change de regular expression with not success. What expression i need to use? In server 2016 the name that Windows assing to the redirect printers is like that : (49 redireccionados(s))

**Comment by zniezelski** [comment]
ManolGa,

try this `( \((\d+) redireccionados\(s\)\))`

please let us know what your system locale is so I can add it to the script. You can find it by running "Get-WinSystemLocale" in powershell.

Thanks,

Zach

**Comment by zniezelski** [comment]
( \((\d+) redireccionados\(s\)\))

**Comment by ManoloGA** [comment]
Hello,

it still does not work

Thank you

LCID             Name             DisplayName
----             ----             -----------
3082             es-ES            Español (España)
![image](https://user-images.githubusercontent.com/44268329/47443162-0f904b80-d7b4-11e8-9a85-719aa5e8fe90.png)

![image](https://user-images.githubusercontent.com/44268329/47443174-16b75980-d7b4-11e8-8212-f08b52f09b61.png)

**Comment by zniezelski** [comment]
Ah the expression got messed up when I sent it. Please view the proper expression in the github website `( \((\d+) redireccionados\(s\)\))`

**Comment by zniezelski** [comment]
![expression](https://user-images.githubusercontent.com/13758216/47444064-a690df80-d783-11e8-9d63-246d7e3a9896.PNG)

**Comment by ManoloGA** [comment]
maybe it's not regular expresision problem ?  I have it working ok in two 2012 server, but in this 2016...
![image](https://user-images.githubusercontent.com/44268329/47481214-2e81f280-d833-11e8-86b5-ea4bfe80479e.png)

**Comment by zniezelski** [comment]
no, I missed up the regular expression again. I had an extra "s" on it. Use this: 

`( \((\d+) redireccionado\(s\)\))`


I'll include a picture too in case it doesn't format correctly.

![picture](https://user-images.githubusercontent.com/13758216/47502286-6427db00-d835-11e8-9f0b-e35b8c35dc8c.PNG)

**Comment by ManoloGA** [comment]
great !! it`s working

**Comment by zniezelski** [comment]
I'm glad its working! Is there no "(s)" on Server 2012?

**Comment by ManoloGA** [comment]
No : 
![image](https://user-images.githubusercontent.com/44268329/47512168-e6d38900-d87b-11e8-80e9-790ff70f184d.png)
