### ISSUE TITLE
Printerceptor and Citrix

### ISSUE THREAD

**Issue by VirtualG20** [zniezelski/Printerceptor#21]
Hello,

I'm trying to get the printerceptor running with a Citix session. I have deployed the driver from a Kyocera FS-1300D (KX) in Print Management and this is also displayed in the Printerceptor GUI. Unfortunately, at the moment I do not find the right regular expression. Button Test = "No Printers match. Check expression and make sure printers ..."
Citrix Printername in German:
Printername + "in Sitzung 4" (in session 4)

could I build a suitable expression here?

Yours sincerely

**Comment by zniezelski** [comment]
Sorry, were you able to resolve this?

**Comment by VirtualG20** [comment]
We have solved the request with the software Thinprint.
