### ISSUE TITLE
WORKS WITH WINDOWS 10?

### ISSUE THREAD

**Issue by evibravo** [zniezelski/Printerceptor#23]
This app works whit win10 pro? or only works whit windows server?

Because no works. easy print is already disabled

error:
no printer match. check expression and make sure printers are available under curren logged in user tha match for testing.

**Comment by zniezelski** [comment]
it should work on windows 10

**Comment by zniezelski** [comment]
sorry I never got back to you. I'm closing the issue but if you need help, open another issue.

Zach
