### ISSUE TITLE
How to refresh the printer list in the "Give full access to printer(s)" column

### ISSUE THREAD

**Issue by ghost** [zniezelski/Printerceptor#24]
Is there some way to refresh the printer list in the "Give full access to printer(s)" column?  Right now when I login with admin rights on a client, it just shows some of the printers from the first user I ran it on.  When I click the Test button at the top, it shows the correct printers.  How can I get that list to populate the right column?  Any help would be greatly appreciated!  Thanks.

**Comment by zniezelski** [comment]
The items listed under "Printers excluded from rename" and "Give full access to printer(s)" are printer drivers that are loaded on the system. If the printer is not showing, the driver will need to be enabled.
