### ISSUE TITLE
Windows Server 2019 (spanish)

### ISSUE THREAD

**Issue by oxto73** [zniezelski/Printerceptor#25]
Hello. I'm trying to configure the server 2019 as if it were server 2016 but it doesn't work for me and I don't know if the problem is in the regular expression --> ( \((\d+) redireccionado\(s\)\)).

Thank you.

**Comment by zniezelski** [comment]
If you login as a user with redirected printers and open up printerceptor and click test regular expression, does it show printers?

Zach

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by zniezelski** [comment]
Can you please tell me your system locale. you can get it by running the powershell command "Get-WinSystemLocale" 

thanks,

Zach

**Comment by oxto73** [comment]
Hello, ok everything. A ")" more, sorry.  

2019 as 2016 then.

Thank you very much.

**Comment by zniezelski** [comment]
everyone is ok now?

Thanks,

Zach

**Comment by oxto73** [comment]
Everything and everyone. Thanks.
