### ISSUE TITLE
Issue with printing server 2019/printer driver

### ISSUE THREAD

**Issue by Mstil** [zniezelski/Printerceptor#26]
I have troubles printing to a Kyocera Ecosys printer on Windows Server 2019 RDS. 
The Printerceptor software does its job. The printer is beiing renamed, but when something is printed, nothing happens. The document is shortly visible in the print queue on the RDS server, but never hits the local queue.
I did test this on another location on a HP printer and that one is working fine.

Could this be a driver issue in combination with this software?
I tried 2 different drivers:
Kyocera ECOSYS M6026cdn v4 KX (PCL6)
Kyocera ECOSYS M6026cdn KX (XPS)

The printer driver for the HP that worked fine was:
HP Laserjet Professional CP1520 Series PCL6

Thanks

**Comment by bust4rhymes** [comment]
> I have troubles printing to a Kyocera Ecosys printer on Windows Server 2019 RDS.
> The Printerceptor software does its job. The printer is beiing renamed, but when something is printed, nothing happens. The document is shortly visible in the print queue on the RDS server, but never hits the local queue.
> I did test this on another location on a HP printer and that one is working fine.
> 
> Could this be a driver issue in combination with this software?
> I tried 2 different drivers:
> Kyocera ECOSYS M6026cdn v4 KX (PCL6)
> Kyocera ECOSYS M6026cdn KX (XPS)
> 
> The printer driver for the HP that worked fine was:
> HP Laserjet Professional CP1520 Series PCL6
> 
> Thanks

I faced the exact issue with Kyocera KM 5050 KX and 3050 KX. I changed the Universal V4 KX Driver for the specific version of each printer. After that i did not have any issues

**Comment by zniezelski** [comment]
Some printer drivers don't work redirected. I noticed a lot of the newer HP drivers just don't work redirected. I always have a bad time with V4 printer drivers. Try finding a V3 PS or PCL driver for the Kyocera.

Zach

**Comment by Mstil** [comment]
> > I have troubles printing to a Kyocera Ecosys printer on Windows Server 2019 RDS.
> > The Printerceptor software does its job. The printer is beiing renamed, but when something is printed, nothing happens. The document is shortly visible in the print queue on the RDS server, but never hits the local queue.
> > I did test this on another location on a HP printer and that one is working fine.
> > Could this be a driver issue in combination with this software?
> > I tried 2 different drivers:
> > Kyocera ECOSYS M6026cdn v4 KX (PCL6)
> > Kyocera ECOSYS M6026cdn KX (XPS)
> > The printer driver for the HP that worked fine was:
> > HP Laserjet Professional CP1520 Series PCL6
> > Thanks
> 
> I faced the exact issue with Kyocera KM 5050 KX and 3050 KX. I changed the Universal V4 KX Driver for the specific version of each printer. After that i did not have any issues

Changing to Universal did the job. Tnx!
