### ISSUE TITLE
Server 2019 Support

### ISSUE THREAD

**Issue by r0h4nh** [zniezelski/Printerceptor#29]
Hello,

Just wondering if this has been tested for Server 2019. I have installed, same procedure as in Server 2012, but so far I am not having any luck with any printers been redirected. I am not getting any information from the log file either.

Thanks.

**Comment by zniezelski** [comment]
it should work on Server 2019. Are you sure the printer is not using easy print?

**Comment by r0h4nh** [comment]
Yes, I am sure. I am using a dot-matrix printer driver. I tried several printers, and non are getting re-created.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SPLNTZ** [comment]
I had issues with Tag printers using Printerceptor back in the day.  It works great with most regular printers, but sadly I had a lot of issue with tag printers. Just a suggestion ThinPrint might be a good solution for dot-matrix printers.  Here’s their website if you want to look at another option. https://www.thinprint.com/en/

Cheers

**Comment by zniezelski** [comment]
What print driver are you using?

**Comment by zniezelski** [comment]
I updated my test server 2019 VM and it worked for me. Make sure you are super for real not using the easy print driver by right clicking on a printer from devices and printers or from a print dialog box and go to "properties", go to "advanced" tab and make sure the driver is not easy print.

Check task scheduler and make sure the task is running when a user logs in. you can also see the task status under "options". 



here is a video of turning off easy print, loading a driver and re-creating the printer with printerceptor https://www.youtube.com/watch?v=VinNQ94PdNA&ab_channel=ZacharyNiezelski

**Comment by zniezelski** [comment]
if the terminal server is on a workgroup, you might have to do this to make it work - https://youtu.be/zUdCcrgMJ9Y

**Comment by r0h4nh** [comment]
I am positive about the print driver. I will reboot the server and check over those settings in the morning, along with the scheduled task.

Thanks.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by zniezelski** [comment]
Were you able to get it working?

Thanks,

Zach

**Comment by r0h4nh** [comment]
Hello,

Had not had a chance to revisit yet, but will let you know. Had to rebuild servers for other reasons.
________________________________
