### ISSUE TITLE
Looping installing

### ISSUE THREAD

**Issue by MartinStarrateit** [zniezelski/Printerceptor#31]
Hi There, 

Please assist with a strange looping of installing as per screenshot. Not sure how this has happened, although it has happened twice now. 

Many Thank
![Image 1755](https://user-images.githubusercontent.com/110673814/183078102-37b9c155-2bd0-4f35-ab3e-87c7c2c9bc24.png)
![Image 1754](https://user-images.githubusercontent.com/110673814/183078111-de40f967-fecb-4303-bbcf-5564931ccd03.png)
s

**Comment by zniezelski** [comment]
Is the problem in the screenshot duplicate printers of the same name? I see there are two "VersaLink B7025 PCL6 - isaiah" 

Is this the "Devices and Printers" window of control panel? That window commonly becomes not accurate\out of sync when printer changes are made programmatically.  Try viewing/managing the printers from a print dialog box by opening notepad and go to print. See if you see the problem from a print dialog box in notepad.

**Comment by zniezelski** [comment]
Martin, were you able to resolve this?

Thanks,

Zach
