### ISSUE TITLE
Error: Access Is Denied

### ISSUE THREAD

**Issue by NielsDebie** [zniezelski/Printerceptor#4]
Dear,

I can change te name of te printer and i can change all the settings of te printer.
Only when i wan't to print someting, I recieve the error ' Access Is Denied' and i can' print.
Do you know what the problem is?
Thanks!

With kind regards,

Niels Debie
![denied](https://cloud.githubusercontent.com/assets/22298329/18636177/2104366a-7e88-11e6-9828-6bc7ab3365fa.png)

**Comment by zniezelski** [comment]
Niels, 

I'm not sure what it will do if you manually change the name of the printer. Give it a try only letting the script rename the printer. Does your user account show in the printer security if you open the "printer properties" of the printer and go to the security tab?

Thanks,

Zach

**Comment by NielsDebie** [comment]
Dear,

Thanks!
The problem was that my account wasn’t set in the security to Manage documents.
Now it works.

Met vriendelijke groeten,
With kind regards,

Niels Debie

[HANDTEKENING]

Hoge Mauw 901, 2370 Arendonk, België
T +32 14 67 87 59 | F +32 14 67 95 26
@ niels@scs.bemailto:niels@scs.be   |   www.scs.behttp://www.scs.be/

Van: zniezelski [mailto:notifications@github.com]
Verzonden: maandag 19 september 2016 16:50
Aan: zniezelski/Printerceptor Printerceptor@noreply.github.com
CC: Niels Debie - S.C.S. Computers bvba niels@scs.be; Author author@noreply.github.com
Onderwerp: Re: [zniezelski/Printerceptor] Error: Access Is Denied (#4)

Niels,

I'm not sure what it will do if you manually change the name of the printer. Give it a try only letting the script rename the printer. Does your user account show in the printer security if you open the "printer properties" of the printer and go to the security tab?

Thanks,

Zach

**Comment by zniezelski** [comment]
Niels,

It sounds like the script isn't adding the proper security to the printer queue it creates. Did the username show at all? Is it a local user or a domain user?

If the account exists as a local and domain user it might not select the proper user account. What is the name of the user logging in that you are using?

The script will remove all the security permissions when the printer is not present on the machine and then re-add them once the printer is accessible again. The problem might have something to do with the printer being renamed, maybe try deleting the printer and let it re-create and see if it works without manually renaming it.

Thanks,

Zach

**Comment by NielsDebie** [comment]
Dear,

My username is shown ‘niels’ and it is a local username.
The username is ‘niels’.
I also have 2 printers (Look at the attachement)
One is ‘Laserjet 500 niels’ and the other ‘Laserjet 500 (redirected 1),2111’
The last one doesn’t work.
I didn’t rename the printer manually, I let the software deside.

Met vriendelijke groeten,
With kind regards,

Niels Debie

[HANDTEKENING]

Hoge Mauw 901, 2370 Arendonk, België
T +32 14 67 87 59 | F +32 14 67 95 26
@ niels@scs.bemailto:niels@scs.be   |   www.scs.behttp://www.scs.be/

Van: zniezelski [mailto:notifications@github.com]
Verzonden: maandag 19 september 2016 16:59
Aan: zniezelski/Printerceptor Printerceptor@noreply.github.com
CC: Niels Debie - S.C.S. Computers bvba niels@scs.be; Author author@noreply.github.com
Onderwerp: Re: [zniezelski/Printerceptor] Error: Access Is Denied (#4)

Niels,

It sounds like the script isn't adding the proper security to the printer queue it creates. Did the username show at all? Is it a local user or a domain user?

If the account exists as a local and domain user it might not select the proper user account. What is the name of the user logging in that you are using?

The script will remove all the security permissions when the printer is not present on the machine and then re-add them once the printer is accessible again. The problem might have something to do with the printer being renamed, maybe try deleting the printer and let it re-create and see if it works without manually renaming it.

Thanks,

Zach

**Comment by NielsDebie** [comment]
Dear,

Forgot the attachement.

Met vriendelijke groeten,
With kind regards,

Niels Debie

[HANDTEKENING]

Hoge Mauw 901, 2370 Arendonk, België
T +32 14 67 87 59 | F +32 14 67 95 26
@ niels@scs.bemailto:niels@scs.be   |   www.scs.behttp://www.scs.be/

Van: zniezelski [mailto:notifications@github.com]
Verzonden: maandag 19 september 2016 16:59
Aan: zniezelski/Printerceptor Printerceptor@noreply.github.com
CC: Niels Debie - S.C.S. Computers bvba niels@scs.be; Author author@noreply.github.com
Onderwerp: Re: [zniezelski/Printerceptor] Error: Access Is Denied (#4)

Niels,

It sounds like the script isn't adding the proper security to the printer queue it creates. Did the username show at all? Is it a local user or a domain user?

If the account exists as a local and domain user it might not select the proper user account. What is the name of the user logging in that you are using?

The script will remove all the security permissions when the printer is not present on the machine and then re-add them once the printer is accessible again. The problem might have something to do with the printer being renamed, maybe try deleting the printer and let it re-create and see if it works without manually renaming it.

Thanks,

Zach

**Comment by zniezelski** [comment]
sorry, I can't receive the attachment. Can you please attach them to the github website comment field of the issue?

Thanks,

Zach

**Comment by zniezelski** [comment]
Niels,

you can also email the attachments to zniezelski@lvtech.net

what printer driver are you using?

Thanks,

Zach

**Comment by NielsDebie** [comment]
Hereby the attachment.
![printers](https://cloud.githubusercontent.com/assets/22298329/18662029/b601f2b2-7f18-11e6-910e-199c0dbcacb1.png)
Dear, I'm using printdriver Hp Universal Printdriver V5.0

**Comment by zniezelski** [comment]
Niels,

I think if the change occurs too fast to the printer this problem can occur. The other issue that is filed on the github page is also related to the HP Universal PCL 5 driver too.

Please try the lastest printer.ps1 commit. I added some delay padding to the parts of the scrip that make changes to the printer:
1. go to https://github.com/zniezelski/Printerceptor/blob/master/printer.ps1 
2. Right click on "raw" and save to C:\program files\printerceptor\printer.ps1
3. go to C:\program files\printerceptor, right click on "printer,ps1" go to "properties" and click "unblock"
4. Open "Printerceptor", go to "options" flip around the values, make "amount of round passes" 5 and "additional wait time in seconds between rounds" 15
5. Give it a try. You might need to reboot the server to make the (Laserjet 500 (redirected 1),2111) printer go away.

Thanks,

Zach

**Comment by zniezelski** [comment]
Niels, 

Have you had a chance to try it with the latest printer.ps1?

Thanks,

Zach

**Comment by NielsDebie** [comment]
Dear,

I logged off the user and back on.
After that, de problem was solved.

Met vriendelijke groeten,
With kind regards,

Niels Debie

[HANDTEKENING]

Hoge Mauw 901, 2370 Arendonk, België
T +32 14 67 87 59 | F +32 14 67 95 26
@ niels@scs.bemailto:niels@scs.be   |   www.scs.behttp://www.scs.be/

Van: zniezelski [mailto:notifications@github.com]
Verzonden: woensdag 21 september 2016 16:07
Aan: zniezelski/Printerceptor Printerceptor@noreply.github.com
CC: Niels Debie - S.C.S. Computers bvba niels@scs.be; Author author@noreply.github.com
Onderwerp: Re: [zniezelski/Printerceptor] Error: Access Is Denied (#4)

Niels,

Have you had a chance to try it with the latest printer.ps1?

Thanks,

Zach

**Comment by zniezelski** [comment]
Niels,

Are you using the latest version of the printer.ps1 and change the relay/round values?

If you didn't, the problem may sometimes continue to occur. More delay seems to keep the changes to the HP Universal 5 driver from messing up.

Thanks,

Zach

**Comment by NielsDebie** [comment]
Dear,

I made the changes.
I will let you know if everything is ok.

Met vriendelijke groeten,
With kind regards,

Niels Debie

[HANDTEKENING]

Hoge Mauw 901, 2370 Arendonk, België
T +32 14 67 87 59 | F +32 14 67 95 26
@ niels@scs.bemailto:niels@scs.be   |   www.scs.behttp://www.scs.be/

Van: zniezelski [mailto:notifications@github.com]
Verzonden: dinsdag 20 september 2016 10:22
Aan: zniezelski/Printerceptor Printerceptor@noreply.github.com
CC: Niels Debie - S.C.S. Computers bvba niels@scs.be; Author author@noreply.github.com
Onderwerp: Re: [zniezelski/Printerceptor] Error: Access Is Denied (#4)

Niels,

I think if the change occurs too fast to the printer this problem can occur. The other issue that is filed on the github page is also related to the HP Universal PCL 5 driver too.

Please try the lastest printer.ps1 commit. I added some delay padding to the parts of the scrip that make changes to the printer:
1.  go to https://github.com/zniezelski/Printerceptor/blob/master/printer.ps1
2.  Right click on "raw" and save to C:\program files\printerceptor\printer.ps1
3.  go to C:\program files\printerceptor, right click on "printer,ps1" go to "properties" and click "unblock"
4.  Open "Printerceptor", go to "options" flip around the values, make "amount of round passes" 5 and "additional wait time in seconds between rounds" 15
5.  Give it a try. You might need to reboot the server to make the (Laserjet 500 (redirected 1),2111) printer go away.

Thanks,

Zach

**Comment by NielsDebie** [comment]
Dear,

I still have a problem on a Windows server 2012 R2 that the security of the Manage documents still is disabled when the user is logged on. So we have to enable it all the time.
Is there a solution for this…

Met vriendelijke groeten,
With kind regards,

Niels Debie

[HANDTEKENING]

Hoge Mauw 901, 2370 Arendonk, België
T +32 14 67 87 59 | F +32 14 67 95 26
@ niels@scs.bemailto:niels@scs.be   |   www.scs.behttp://www.scs.be/

Van: zniezelski [mailto:notifications@github.com]
Verzonden: donderdag 22 september 2016 16:17
Aan: zniezelski/Printerceptor Printerceptor@noreply.github.com
CC: Niels Debie - S.C.S. Computers bvba niels@scs.be; Author author@noreply.github.com
Onderwerp: Re: [zniezelski/Printerceptor] Error: Access Is Denied (#4)

Niels,

Are you using the latest version of the printer.ps1 and change the relay/round values?

If you didn't, the problem may sometimes continue to occur. More delay seems to keep the changes to the HP Universal 5 driver from messing up.

Thanks,

Zach

**Comment by zniezelski** [comment]
Niels,

Does this consistently occur or did this just start happening? Does the user at least show in security with "print" and "manage this printer" permissions?

The script does not set "manage documents", do you require that option for something specific?

Zach

**Comment by zniezelski** [comment]
Niels,

Please make sure you have all of the windows updates applied. I know the script has problems setting security settings on Server 2008 if it isn't updated. I'm not sure which specific windows update fixes the problem but make sure your server is Windows updated.

Zach

**Comment by zniezelski** [comment]
Neils,

If its ok with you I could remote desktop in and take a look at it if you'd like.

Thanks,

Zach

**Comment by NielsDebie** [comment]
Dear,

Ok. I wil make an update and keep you updated.

Met vriendelijke groeten,
With kind regards,

Niels Debie

[HANDTEKENING]

Hoge Mauw 901, 2370 Arendonk, België
T +32 14 67 87 59 | F +32 14 67 95 26
@ niels@scs.bemailto:niels@scs.be   |   www.scs.behttp://www.scs.be/

Van: zniezelski [mailto:notifications@github.com]
Verzonden: dinsdag 27 september 2016 13:18
Aan: zniezelski/Printerceptor Printerceptor@noreply.github.com
CC: Niels Debie - S.C.S. Computers bvba niels@scs.be; Author author@noreply.github.com
Onderwerp: Re: [zniezelski/Printerceptor] Error: Access Is Denied (#4)

Niels,

Please make sure you have all of the windows updates applied. I know the script has problems setting security settings on Server 2008 if it isn't updated. I'm not sure which specific windows update fixes the problem but make sure your server is Windows updated.

Zach

**Comment by zniezelski** [comment]
Niels,

Have you had any success?

Zach

**Comment by NielsDebie** [comment]
Dear,

I still have the problem, after a full restart.
Can you send me the latest version of the software?

Met vriendelijke groeten,
With kind regards,

Niels Debie

[HANDTEKENING]

Hoge Mauw 901, 2370 Arendonk, België
T +32 14 67 87 59 | F +32 14 67 95 26
@ niels@scs.bemailto:niels@scs.be   |   www.scs.behttp://www.scs.be/

Van: zniezelski [mailto:notifications@github.com]
Verzonden: dinsdag 4 oktober 2016 15:36
Aan: zniezelski/Printerceptor Printerceptor@noreply.github.com
CC: Niels Debie - S.C.S. Computers bvba niels@scs.be; Author author@noreply.github.com
Onderwerp: Re: [zniezelski/Printerceptor] Error: Access Is Denied (#4)

Niels,

Have you had any success?

Zach

**Comment by zniezelski** [comment]
Niels,

Would you still like assistance with this problem?

Thanks,

Zach

**Comment by NielsDebie** [comment]
Dear,

This problem is ‘solved’.
Thanks.

Met vriendelijke groeten,
With kind regards,

Niels Debie

[HANDTEKENING]

Hoge Mauw 901, 2370 Arendonk, België
T +32 14 67 87 59 | F +32 14 67 95 26
@ niels@scs.be<mailto:niels@scs.be>   |   www.scs.be<http://www.scs.be/>

Van: zniezelski [mailto:notifications@github.com]
Verzonden: donderdag 22 december 2016 1:04
Aan: zniezelski/Printerceptor <Printerceptor@noreply.github.com>
CC: Niels Debie - S.C.S. Computers bvba <niels@scs.be>; Author <author@noreply.github.com>
Onderwerp: Re: [zniezelski/Printerceptor] Error: Access Is Denied (#4)


Niels,

Would you still like assistance with this problem?

Thanks,

Zach

**Comment by NielsDebie** [comment]
Dear,

I just installed the software on a Windows Server 2012 R2 But I can’t get it working.
My printer still calls redirected ‘7’. The drivers local and in the cloud are the same.


Met vriendelijke groeten,
With kind regards,

Niels Debie

[HANDTEKENING]

Hoge Mauw 901, 2370 Arendonk, België
T +32 14 67 87 59 | F +32 14 67 95 26
@ niels@scs.be<mailto:niels@scs.be>   |   www.scs.be<http://www.scs.be/>

Van: zniezelski [mailto:notifications@github.com]
Verzonden: donderdag 22 december 2016 1:04
Aan: zniezelski/Printerceptor <Printerceptor@noreply.github.com>
CC: Niels Debie - S.C.S. Computers bvba <niels@scs.be>; Author <author@noreply.github.com>
Onderwerp: Re: [zniezelski/Printerceptor] Error: Access Is Denied (#4)


Niels,

Would you still like assistance with this problem?

Thanks,

Zach

**Comment by zniezelski** [comment]
If you open up printer properties of the redirected printer, is it using the easy print driver or does it show the vendor driver?

Make sure Easy Print is not the first choice. It can be disabled in group policy.

Thanks,

Zach

**Comment by zniezelski** [comment]
Niels,

Were you able to get the script working in 2012 R2?

Zach

**Comment by NielsDebie** [comment]
Dear,

No, didn’t work.

Met vriendelijke groeten,
With kind regards,

Niels Debie

[HANDTEKENING]

Hoge Mauw 901, 2370 Arendonk, België
T +32 14 67 87 59 | F +32 14 67 95 26
@ niels@scs.be<mailto:niels@scs.be>   |   www.scs.be<http://www.scs.be/>

Van: zniezelski [mailto:notifications@github.com]
Verzonden: zaterdag 14 januari 2017 22:48
Aan: zniezelski/Printerceptor <Printerceptor@noreply.github.com>
CC: Niels Debie - S.C.S. Computers bvba <niels@scs.be>; Author <author@noreply.github.com>
Onderwerp: Re: [zniezelski/Printerceptor] Error: Access Is Denied (#4)


Niels,

Were you able to get the script working in 2012 R2?

Zach

**Comment by zniezelski** [comment]
Neils,

if your machine is not joined to a domain, you will need to make this change.

https://youtu.be/zUdCcrgMJ9Y

Let me know if this helps or not.

Thanks,

Zach
