### ISSUE TITLE
Local printer not showen

### ISSUE THREAD

**Issue by jvdhsystem** [zniezelski/Printerceptor#5]
Hello,

Why is my local printer SHARP not showen in the overview? When th click on TEST, then I see them as well.
![printerceptor](https://cloud.githubusercontent.com/assets/23010642/19625403/aecc0df2-9917-11e6-950c-9cf470bee91a.PNG)

**Comment by zniezelski** [comment]
The "Test" button tests the regular expression only. It will only list printers that match the expression under the logged in user account. 

If you want to rename or give full access to your redirected sharp printer, you must have the driver configured on the server and make the easy print driver not the first choice. The script will not work with printers that use the easy print driver. 

Let me know if you need further assistance.

Thanks for using the script,

Zach

**Comment by zniezelski** [comment]
The reason the sharp printer is not listed as a driver is because the driver is not installed on the system. You must be using the easy print driver for the redirected printer.

Install the same driver that the client workstations have using print management.

**Comment by zniezelski** [comment]
here is a little video with some instruction in the description of what I think you need to do: https://www.youtube.com/watch?v=VinNQ94PdNA&feature=youtu.be

if you are only looking to rename the printer you will just need to make sure you hit "save" once in printerceptor. If you want full re-creation, make sure you check the box in printerceptor and hit save.

**Comment by zniezelski** [comment]
Were you able to get setup? 

Zach

**Comment by jvdhsystem** [comment]
Hello Zach,

I have a problem with printermagement tool.
I try to add feature Print and document service but get error code 0x800F0922.
I created a ticket at Microsoft.
Sunday I had more than a hours contact with support but could not find a solution.
They took some logs and will analyses and will contact me again, but till now no contacts or mails from Microsoft.

Met vriendelijke groeten,

Jeff Van den Heuvel
JVDH-SYSTEM bvba
Steenweg op Turnhout 86
2330 Merksplas
Tel. 014/63.11.24
GSM 0495/24.68.66
www.jvdh-system.behttp://www.jvdh-system.be

**Comment by jvdhsystem** [comment]
Thanks!

Met vriendelijke groeten,

Jeff Van den Heuvel
JVDH-SYSTEM bvba
Steenweg op Turnhout 86
2330 Merksplas
Tel . 014/63.11.24
GSM 0495/24.68.66
www.jvdh-system.behttp://www.jvdh-system.be/

Van: zniezelski [mailto:notifications@github.com]
Verzonden: zondag 23 oktober 2016 14:04
Aan: zniezelski/Printerceptor Printerceptor@noreply.github.com
CC: Jeff Van den Heuvel Jeff@jvdh-system.be; Author author@noreply.github.com
Onderwerp: Re: [zniezelski/Printerceptor] Local printer not showen (#5)

here is a little video with some instruction in the description of what I think you need to do: https://www.youtube.com/watch?v=VinNQ94PdNA&feature=youtu.be

if you are only looking to rename the printer you will just need to make sure you hit "save" once in printerceptor. If you want full re-creation, make sure you check the box in printerceptor and hit save.

**Comment by jvdhsystem** [comment]
Hello Zach,

Thanks for the reaction.
Did you have an example how to install the driver?

Met vriendelijke groeten,

Jeff Van den Heuvel
JVDH-SYSTEM bvba
Steenweg op Turnhout 86
2330 Merksplas
Tel . 014/63.11.24
GSM 0495/24.68.66
www.jvdh-system.behttp://www.jvdh-system.be/

Van: zniezelski [mailto:notifications@github.com]
Verzonden: zondag 23 oktober 2016 13:37
Aan: zniezelski/Printerceptor Printerceptor@noreply.github.com
CC: Jeff Van den Heuvel Jeff@jvdh-system.be; Author author@noreply.github.com
Onderwerp: Re: [zniezelski/Printerceptor] Local printer not showen (#5)

The reason the sharp printer is not listed as a driver is because the driver is not installed on the system. You must be using the easy print driver for the redirected printer.

Install the same driver that the client workstations have using print management.

**Comment by jvdhsystem** [comment]
Hello Zach,

There is a problem.
The renamed redirected printer disappears from the session.

I have changed the rename to the printername, without extension of username.

The software supplier told me that they need a unique printername and same for all the users.

So I changed it :
[cid:image001.png@01D23EA7.B82C3090]

Printer :
[cid:image002.png@01D23EA7.B82C3090]

What could be the problem on the server that the printer at the user session disappears?

Met vriendelijke groeten,

Jeff Van den Heuvel
JVDH-SYSTEM bvba
Steenweg op Turnhout 86
2330 Merksplas
Tel . 014/63.11.24
GSM 0495/24.68.66
www.jvdh-system.behttp://www.jvdh-system.be/

Van: zniezelski [mailto:notifications@github.com]
Verzonden: dinsdag 25 oktober 2016 4:23
Aan: zniezelski/Printerceptor Printerceptor@noreply.github.com
CC: Jeff Van den Heuvel Jeff@jvdh-system.be; Author author@noreply.github.com
Onderwerp: Re: [zniezelski/Printerceptor] Local printer not showen (#5)

Were you able to get setup?

Zach

**Comment by zniezelski** [comment]
The printer needs to have a unique name. It might disappear if another user logs in and the name changes to a name of an already existing printer.

Can you please send the pictures a different way, I was unable to view them.

thanks,

Zach

**Comment by jvdhsystem** [comment]
Hello Zach,

Here the mail again, attach

Met vriendelijke groeten,

Jeff Van den Heuvel
JVDH-SYSTEM bvba
Steenweg op Turnhout 86
2330 Merksplas
Tel . 014/63.11.24
GSM 0495/24.68.66
www.jvdh-system.behttp://www.jvdh-system.be/

Van: zniezelski [mailto:notifications@github.com]
Verzonden: maandag 14 november 2016 18:52
Aan: zniezelski/Printerceptor Printerceptor@noreply.github.com
CC: Jeff Van den Heuvel Jeff@jvdh-system.be; Author author@noreply.github.com
Onderwerp: Re: [zniezelski/Printerceptor] Local printer not showen (#5)

The printer needs to have a unique name. It might disappear if another user logs in and the name changes to a name of an already existing printer.

Can you please send the pictures a different way, I was unable to view them.

thanks,

Zach

**Comment by jvdhsystem** [comment]
Hello Zach,

Why disappear the printer at user level?
My client angry why it is not working as expected.
Users do not change there printernames.

Met vriendelijke groeten,

Jeff Van den Heuvel
JVDH-SYSTEM bvba
Steenweg op Turnhout 86
2330 Merksplas
Tel. 014/63.11.24
GSM 0495/24.68.66
www.jvdh-system.behttp://www.jvdh-system.be

From: Jeff Van den Heuvel
Sent: maandag 14 november 2016 19:06
To: zniezelski/Printerceptor reply@reply.github.com; zniezelski/Printerceptor Printerceptor@noreply.github.com
Cc: Author author@noreply.github.com
Subject: RE: [zniezelski/Printerceptor] Local printer not showen (#5)

Hello Zach,

Here the mail again, attach

Met vriendelijke groeten,

Jeff Van den Heuvel
JVDH-SYSTEM bvba
Steenweg op Turnhout 86
2330 Merksplas
Tel . 014/63.11.24
GSM 0495/24.68.66
www.jvdh-system.behttp://www.jvdh-system.be/

Van: zniezelski [mailto:notifications@github.com]
Verzonden: maandag 14 november 2016 18:52
Aan: zniezelski/Printerceptor <Printerceptor@noreply.github.com<mailto:Printerceptor@noreply.github.com>>
CC: Jeff Van den Heuvel <Jeff@jvdh-system.be<mailto:Jeff@jvdh-system.be>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Onderwerp: Re: [zniezelski/Printerceptor] Local printer not showen (#5)

The printer needs to have a unique name. It might disappear if another user logs in and the name changes to a name of an already existing printer.

Can you please send the pictures a different way, I was unable to view them.

thanks,

Zach

**Comment by zniezelski** [comment]
You cannot do what you are trying to do with a redirected printer.

Each user must have a unique printer name. This is why by default windows uses the user's session number.

Printerceptor can change the name to something that will be consistent but it must still be unique using the users username or client name. 

This is an example what is happening to you:

User 1 and User 2 have the local printer HP Officejet Pro 8600 (Network) on their workstations.

User 1 logs into the terminal server and Printerceptor renames Printer "HP Officejet Pro 8600 (Network) Redirected 5" to "HP Officejet Pro 8600 (Network)" and its ok until User 2 logs in.

User 2 logs into the terminal server and "HP Officejet Pro 8600 (Network) Redirected 55"  and is renamed to "HP Officejet Pro 8600 (Network)". It screws up User 1 because their printer was the same non unique name and it disappears because now User 2 has the printer.

Configure the printer locally on the server if the user is in the same network as the printer everyone is using or use a VPN or IP printing. 

Good Luck,

Zach

**Comment by jvdhsystem** [comment]
Hello Zach,

Thanks for your explanation.
I will forward this to the software vendor.

Met vriendelijke groeten,

Jeff Van den Heuvel
JVDH-SYSTEM bvba
Steenweg op Turnhout 86
2330 Merksplas
Tel. 014/63.11.24
GSM 0495/24.68.66
www.jvdh-system.behttp://www.jvdh-system.be
