### ISSUE TITLE
Printer Disappearing - Overlapping User Conflict (local and domain existence)

### ISSUE THREAD

**Issue by fgmike** [zniezelski/Printerceptor#8]
Hi,

have installed as directed, psconfig working. When ever we try to apply full permissions to a printer the printer disappears.

We have rebooted, checked all updates and it still disappears.

We have installed the correct drivers and disabled EasyPrint.

Are there any other reliance's we should know about or ways we could pass information to get this working ?
As this would be exceptionally helpful if we can get it working in our environment.

Server 2012R2 fully patched. 3.5 .Net installed and Printer Management role installed.

Thanks in Advance.

**Comment by zniezelski** [comment]
Which print driver are you using? I'll try recreating the problem.

Thanks,

Zach

Sent from my Windows Phone
________________________________
From: fgmike
Sent: 12/20/2016 10:55 PM
To: zniezelski/Printerceptor
Cc: Subscribed
Subject: [zniezelski/Printerceptor] Printer Disappearing (#8)


Hi,

have installed as directed, psconfig working. When ever we try to apply full permissions to a printer the printer disappears.

We have rebooted, checked all updates and it still disappears.

We have installed the correct drivers and disabled EasyPrint.

Are there any other reliance's we should know about or ways we could pass information to get this working ?
As this would be exceptionally helpful if we can get it working in our environment.

Thanks in Advance.

-

**Comment by zniezelski** [comment]
Also please let me know the operating system and open print management from the script and see if it is showing the printer in there. If the script isn't adding the proper security to the recreated printer then it would show in print management (ran as system account from script) and it would not display. 

Thanks,

Zach

**Comment by zniezelski** [comment]
If the script is running really fast before the redirected printers get a chance to fully install it could also cause trouble. Please try going to "options" and flip the values. Make rounds 5 and wait time 15.

Thanks,

Zach

**Comment by fgmike** [comment]
Hi Zach,

Thanks so much for coming back to me.

I loaded up the psconfig and the printer is in there even though it does not display in the devices & printers. It would appears permissions are not being set as you suggested.

When I check the permissions on the printer I noticed that it was setting the Local Administrator was getting the permissions for the printer. We solved the issue by renaming the local administrator to something different than the Domain Admin Account.

All good in the world now, works as expected. Thought you would like to know just in case someone else blames your script for this oversight ☺



Regards,

Michael Clisby
Technology Manager
Email: mclisby@theflynngroup.com.au<mailto:mclisby@theflynngroup.com.au>
Website: www.theflynngroup.com.au<http://www.theflynngroup.com.au/>
Office: (07) 4987 5595
Mobile: 0421 385 385

 [Email---Signature-TFG-small]

**Comment by zniezelski** [comment]
Michael,

I’m glad you got it sorted out! I’ll fix the problem on the next release and add something to the release page regarding the overlapping user conflict problem.

Thanks for troubleshooting and using the script!

Zach

**Comment by fg-tech** [comment]
Hi Zach,

I'm not sure if this is quite the same problem, but a similar issue is occurring on a WinSvr2012R2 RDS.
There doesn't appear to be any overlapping local and domain accounts, and some domain accounts are working, however there are a few domain accounts that do not.

These domain accounts have the login profile name structure of:
domain\username
username@emaildomain

Where the domain and the email domain are different. Would this be having an effect in the code? Do you use specific user identifiers, that could mismatch between Printerceptor and the User Session?

Thanks,
Lachlan

**Comment by zniezelski** [comment]
Lachlan,

The script looks up username and uses the SID. The overlap problem exists because it looks for the username locally first I think. 

Can you give me some sample usernames/domains that I could use to try re-creating the problem?

Do you have Powershell 3.0 installed?

If you open up "Print Management" from the GUI, what does the printer security look like?

Thanks,

Zach

**Comment by fg-tech** [comment]
Hi Zach,

Powershell 3.0 is installed. In Print Management, the new local print queue never appears. From either the user view or the administrator's view.

I'll get you some examples soon.

Regards,
Lachlan Curnow


On 25 Jan 2017, at 11:26 AM, zniezelski <notifications@github.com<mailto:notifications@github.com>> wrote:


Lachlan,

The script looks up username and uses the SID. The overlap problem exists because it looks for the username locally first I think.

Can you give me some sample usernames/domains that I could use to try re-creating the problem?

Do you have Powershell 3.0 installed?

If you open up "Print Management" from the GUI, what does the printer security look like?

Thanks,

Zach

-

**Comment by zniezelski** [comment]
Lachlan,

It sounds like the printer is not being created. One thing that might help determine where the fault is:

1. create a local printer that has a redirected printer like name for testing "PrinterName (redirected 1)"
2. Make sure printerceptor is set to recreate the driver you picked for the test printer
3. Manually run printer.ps1 from the C:\Program Files\Printerceptor folder
4. Note any errors in the Output. It might help figure out what is happening. 

Thanks,

Zach

**Comment by zniezelski** [comment]
Lachlan,

You may need to give "everyone", "Manage Server" permissions in print management. 

I recently found this seems to occur on server that is not joined to a domain.

Thanks,

Zach

**Comment by zniezelski** [comment]
this problem has been fixed in the 4.0 Release. I'm closing the issue.
