### ISSUE TITLE
Printer Disappears - Host on Workgroup

### ISSUE THREAD

**Issue by eluich** [zniezelski/Printerceptor#9]
Hi

I'm trying to configure Printerceptor on RDS Windows Server 2016.
The installation seems good but my printer RICOH Aficio MP C3502 PCL 6 don't appear in devices and printers.
In Event Log the operation is done
![capture](https://cloud.githubusercontent.com/assets/25503784/22546879/3ad0494a-e93f-11e6-9872-ab0edb4eb6ca.JPG)

If i just test to rename printer it's working.

Have you got a idea to résolve my issue ?

Sorry for my bad english :)

Best Regards

**Comment by zniezelski** [comment]
Eluich,

The printer security is probably not being applied due to the known user overlapping issue. You may have a user named "administrator" locally and a user named "Administrator" on the domain. The script isn't applying security to the printer queue with the correct username.

Try a different user account and see if it works. The problem should be resolved soon in the next release.

Thanks,

Zach

**Comment by zniezelski** [comment]
Eluich, 

Please let me know the system locale language you use and your regular expression. I'd like to add it to the next release.

Thanks,

Zach

**Comment by eluich** [comment]
Hi Zach

I tried with a different user but the problem is the same, the printer doesn't create

The system locale language is French and my regular expression is ( \(redirection de (\d+)\))

Best Regards

**Comment by zniezelski** [comment]
If you open print management up from the script GUI, does it show the newly created printer?

Zach

**Comment by zniezelski** [comment]
under "options" try flipping the values to "5" passes and "15" wait seconds. The script might be taking action too fast.

**Comment by eluich** [comment]
In Print Management the printer isn't created 
If i change the options values the problem is the same
![capture](https://cloud.githubusercontent.com/assets/25503784/22551475/42609fb4-e955-11e6-9a98-df15ea1dfa5c.JPG)

**Comment by zniezelski** [comment]
Would it be possible to remote in over RDP and troubleshoot?

Zach

**Comment by eluich** [comment]
yes no problem. You need adminstrator account or a simply user with restrictive privilege ?

**Comment by zniezelski** [comment]
probably just a normal account that can RDP in will be fine. 

Zach

**Comment by zniezelski** [comment]
please give the account full access to the C:\program files\printerceptor folder. Or if you are ok with Just giving me administrator access then that will work too.

**Comment by eluich** [comment]
Ok can you send information to private email ?

**Comment by zniezelski** [comment]
sent it to zniezelski@lvtech.net

**Comment by eluich** [comment]
Email is done

Thx

**Comment by zniezelski** [comment]
eluich,

Thanks for reporting this!

I troubleshot and found this problem occurs with the script on all hosts that are not joined to the domain. The best solution I have right now is to add "Manage Server" permissions for "everyone" in the Printer Management mmc. 

I modified the release notes to include this in the installation instruction:

If the host is on a workgroup, give "everyone" "Manage Server" permissions of the print server in Print Management. The printer will disappear if you don't do this. https://youtu.be/zUdCcrgMJ9Y

**Comment by zniezelski** [comment]
Eluich,

Is everything working ok for you? Let me know if you need further assistance.

Thanks,

Zach

**Comment by eluich** [comment]
Hi Zach

Actually it's ok for me.
Thank you for your assistance

Best Regards

Le 14 févr. 2017 3:55 AM, "zniezelski" <notifications@github.com> a écrit :

Eluich,

Is everything working ok for you? Let me know if you need further
assistance.

Thanks,

Zach

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zniezelski/Printerceptor/issues/9#issuecomment-279593090>,
or mute the thread
